### ISSUE TITLE
DefaultValue attribute

### ISSUE THREAD

**Issue by sramaccini** [zabute/formsy-semantic-ui-react#1]
It seems that Input is missing support for the defaultValue attribute. How do I assign a default value to the input field ?

**Comment by zabute** [comment]
Thanks for pointing that out. You should now be able to set default values in ```0.1.5```
```jsx
<Input name="inputName" defaultValue="123" ... />
<TextArea name="textAreaName" defaultValue="xyz" ... />
```
Also note that when resetting the form, you'll have to specify the inputs with their default values like so:
```js
this.refs.formRef.reset({
  inputName: "123",
  textAreaName: "xyz"
})
```

**Comment by sramaccini** [comment]
The same applies also to Dropdown. It seems that it is missing support for the DefaultValue attribute.
