### ISSUE TITLE
[Feature] Field-controlled `Search` example

### ISSUE THREAD

**Issue by AlbinoGeek** [zabute/formsy-semantic-ui-react#106]
I would love to have an input that accepts a user value, and/or shows a dropdwon (such as `Search` does in semantic-ui, or `Autocomplete` does in material-ui.) It looks like `Search` has an `input` property which accepts a Component, so it may be wrappable with formsy?

**Comment by felixmosh** [comment]
You can wrap it manually, or provide it the formsy-input
