### ISSUE TITLE
`@types/hoist-non-react-statics` to `devDependencies` ?

### ISSUE THREAD

**Issue by AlbinoGeek** [zabute/formsy-semantic-ui-react#107]
I was surprised when I was reviewing the npmjs page for this project and found it had a `@types` package dependency required, thinking this to be rather peculiar.

**Comment by felixmosh** [comment]
It was like that, and it not worked properly,

https://github.com/zabute/formsy-semantic-ui-react/commit/f8653793d82570aa98ab61c63ad58ead51897932#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by AlbinoGeek** [comment]
Apologies, good to know!
