### ISSUE TITLE
`Checkbox` with `defaultChecked={true} required` does not validate the Form

### ISSUE THREAD

**Issue by AlbinoGeek** [zabute/formsy-semantic-ui-react#108]
I have a form that is essentially all required Checkboxes, state hydrated on refresh (making them "pre-checked").

It is worth noting that initial validation runs on Inputs, but not Checkbox. (e.g: This same form setup works with `Input`.)

## Expected Behavior
A form consisting of required-but-already-checked Checkboxes should be valid on load, not invalid.

The user should load into a (not disabled) Next button.

## Current Behavior
When a Checkbox is a toggle, default's Checked (or restores a `value={true}` on hydrate) -- and is also `required`, the user is forced to Uncheck and Recheck the Checkbox before the Next button becomes available within the form (due to `Formsy.onValid`)

The user loads into a disabled Next button, even if the `Checkbox`'s `defaultChecked` is `true`.

## Steps to Reproduce
```tsx
import { Form } from 'formsy-semantic-ui-react'
import { Button } from 'semantic-ui-react'

// matches Formsy.onChange, re-used elsewhere in my code
export type OnChangeProp = {
  onChange: (currentValues: Values, isChanged: boolean) => void
}

const Example: FC<OnChangeProp & { defaults: { AgreeMSA: boolean } }> = ({
  defaults,
  onChange,
}) => {
  const [nextDisabled, setNextDisabled] = useState<boolean>(true)

  // defaults.AgreeMSA is a boolean "true" on page refresh
  // onChange saves and sets `defaults`, triggering update
  // defaults is stored/retrieved from localStorage as JSON

  return (
    <Form
      onChange={onChange}
      onValid={() => setNextDisabled(false)}
      onInvalid={() => setNextDisabled(true)}
    >
      <Form.Group>
        <Form.Checkbox
          defaultChecked={defaults.AgreeMSA}
          name="AgreeMSA"
          label="Agree to the Terms of Service"
          required
          toggle
          validations="isTrue"
        />
      </Form.Group>
      <Button fluid primary disabled={nextDisabled}>
        Next
      </Button>
    </Form>
  )
}
```

**Comment by felixmosh** [comment]
you can pass `value` attribute if you want to run the validation at the initial phase,

https://codesandbox.io/s/adoring-cohen-i3p00?file=/src/App.tsx

**Comment by AlbinoGeek** [comment]
I was under the impression `checked` was the attribute to use for Checkboxes, fair.

https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attribute

**Comment by felixmosh** [comment]
`value` is the value that **formsy** stores inside it self (and validates) for each input.
