### ISSUE TITLE
If there is onChange prop inside Select, the value changed is not reflected in UI 

### ISSUE THREAD

**Issue by KaliCharanV** [zabute/formsy-semantic-ui-react#13]
<Form.Select label='Sender Type' required name='sourceType' placeholder='Sender Type'
              options={sourceTypes} search onChange={props.sourceTypeChanged} />
The onChange function gets called; but the value is not reflecting in the Select field.

One solution that I figured out is to use the semantic-ui-react form only for select field.
But the formsyForm won't validate these fields

**Comment by zabute** [comment]
Yeah. Its not just ```Select```. ```setValue()``` wont be called on any of the inputs if you provide a change handler. I'll fix this asap. For now, avoid ```onChange``` on the inputs and only use it on the ```Form```. See [here](https://github.com/christianalfoni/formsy-react/blob/master/API.md#onchange)

**Comment by KaliCharanV** [comment]
Thanks, solves my problem.

**Comment by zabute** [comment]
fixed in ```0.2.8``` (58d6eeff57d8d80a1e82a9749c2fbb7be2984c99)
