### ISSUE TITLE
Unwanted `required` prop passed through automatically

### ISSUE THREAD

**Issue by noinkling** [zabute/formsy-semantic-ui-react#18]
Formsy uses the `required` prop to signal that a field shouldn't be empty. When specified, this library also passes it through to Semantic's component, causing it to display some extra styling when there is a label (a red asterisk in the default theme). However in certain cases it is desirable to keep the validation, but avoid the styling, such as with a login form. I couldn't find any workaround to achieve this other than overriding the CSS.

**Comment by iwllyu** [comment]
The styling comes from the required prop on the Form.Field in the component. You can remove it from there if you want the red asterisk to not show up.

**Comment by noinkling** [comment]
Right, I can remove it by modifying the library, but there's no way to do so from my application code. In vanilla Semantic-UI-React `required` similarly has both a functional and a stylistic purpose: the input gets marked with the html `required` attribute in addition to the styling, but at least in that case I can add the attribute while avoiding the styling by doing `input={{ required: true }}` or using the children syntax for `Form.Field`. I don't have a problem in principle with having a prop control both function and style, it's a very common thing to do, but I feel like this is one of those rare instances where it would be nice to have a bit more flexibility, maybe with an override like:

```jsx
import { Form } from 'formsy-semantic-ui-react';
...
<Form.Input required fieldProps={{ required: false }} />
```

Actually, looking at the code, I'm not sure why this library doesn't just delegate as much as it can to the original components like a normal HOC would do. `Form.Field` can't actually receive any props other than `error` and `required`, which is why you can't use the `width` prop from your own issue (#17). I might just end up making my own wrappers and possibly turning that into a PR.

To be honest I did end up finding a workaround for my particular issue, which was to add a custom validator to Formsy.

**Comment by zabute** [comment]
I agree that having a way to prevent the ```required``` prop from being passed to the ```Form.Field``` while letting formsy know its required is convenient. However, I think the ```fieldProps={{}}``` can just be a boolean flag (```showRequiredField``` sound good?) and pass any other props like you would when using vanilla SUIR. 

And yes, the ```Form.Field``` is not getting the props it needs like ```width``` and  ```className``` etc. I'll fix this asap.

**Comment by noinkling** [comment]
Yup a boolean is fine as well. `showRequiredField` is a little confusing though, maybe something more like `passRequired` or `passRequiredToField`? It should probably default to `true` so you would have to explicitly specify `passRequiredToField={false}`. Or else make it a negative, e.g. `dontPass...`. Thanks for taking a look.

**Comment by zabute** [comment]
```0.2.10``` now lets you pass  ```passRequiredToField={false}``` . Closing.
