### ISSUE TITLE
TypeError: Cannot read property 'attachToForm' of undefined

### ISSUE THREAD

**Issue by RobinKuiper** [zabute/formsy-semantic-ui-react#21]
Just tried this, but I get:

[Error Screenshot](https://i.imgur.com/RnHYyKM.png)

I import:

`import { Form, Input, TextArea, Checkbox, Radio, RadioGroup, Dropdown, Select } from 'formsy-semantic-ui-react';`

And this is my form:

[Form Screenshot](https://i.imgur.com/7HeyaSE.png)

Am I doing anything wrong?

**Comment by zabute** [comment]
I couldn't reproduce this error. This should work.

If you can create a repo that reproduces this error, I could take a look at that find out whats wrong.

**Comment by RobinKuiper** [comment]
Don't know what was wrong exactly, but after re-adding formsy-react and this package, everyting worked fine.
