### ISSUE TITLE
Trigger submit from code

### ISSUE THREAD

**Issue by mikerussellnz** [zabute/formsy-semantic-ui-react#22]
I want to have a form as part of a wizard that has a number of steps.  The next button should submit the form but the next button is outside the form.

I have read about calling this. firm.submit() but it doesn't work for me (https://github.com/christianalfoni/formsy-react/issues/45)

**Comment by mikerussellnz** [comment]
Ok, I figured it out.

For anyone who needs this, the formsy form is available as formsyForm. 

So you can use this to trigger the submit:

this.form.formsyForm.submit();

**Comment by zabute** [comment]
Reopening because ```Form```  is supposed to expose formsy's and SUIR's apis. You certainly shouldn't have to go digging into the source just to be able to submit the form from code. The next release will have better api parity with formsy. PRs are welcome.

**Comment by zabute** [comment]
fixed in 0.3.0
