### ISSUE TITLE
Can't resolve 'formsy-react'

### ISSUE THREAD

**Issue by srdjanRakic** [zabute/formsy-semantic-ui-react#24]
Module not found: 
Can't resolve 'formsy-react' in 'C:\Source\node_modules\formsy-semantic-ui-react\lib'

**Comment by zabute** [comment]
Did you install  ```formsy-react```? Its a peer dependency. Must also be ```>= 1.1.1```

**Comment by srdjanRakic** [comment]
Yeah, I have installed v1.3.2. Everything works when I import formsy-react into mine entry index.js file, but I do not want to do that. :)

**Comment by zabute** [comment]
Ok. I'll look into this.

**Comment by zabute** [comment]
@srdjanRakic  I couldn't reproduce this issue with create-react-app. If you could upload a repo that can demonstrate this issue, It would help me track the issue down.

**Comment by srdjanRakic** [comment]
Weird, I could not reproduce it also. I am closing the issue. Thanks Zabute. 👍
