### ISSUE TITLE
Allow labels

### ISSUE THREAD

**Issue by chadwilken** [zabute/formsy-semantic-ui-react#3]
Would it be possible to get label support? I attempted to use `inline={false}` but it apparently doesn't allow label usage.

Thanks for the library though, it makes my life a lot easier.

**Comment by zabute** [comment]
```<Input/>``` supports having a [label attached to it](http://react.semantic-ui.com/maximize/input-example-labeled). So you can do this:

```jsx
import Formsy from 'formsy-react'
import { Input } from 'formsy-semantic-ui-react';

<Formsy.Form>
 <Input
   name="fname"
   label="First Name"
 />
</Formsy.Form>

```
![screenshot from 2017-03-21 10-42-04](https://cloud.githubusercontent.com/assets/4171528/24137368/767732d8-0e24-11e7-9168-c0a758376ea4.png)


Or  wrap any of the compoents with ```Form.Field```:
```jsx
import Formsy from 'formsy-react';
import { Form } from 'semantic-ui-react';
import { Input } from 'formsy-semantic-ui-react';

<Formsy.Form>
  <Form.Field>
    <label> First Name </label>
    <Input
     name="fname"
    />
 </Form.Field>
</Formsy.Form>
```
![screenshot from 2017-03-21 10-44-27](https://cloud.githubusercontent.com/assets/4171528/24137563/59c06eb0-0e25-11e7-8d28-e670882609ff.png)


Let me know if this doesn't solve your problem.

**Comment by zabute** [comment]
@chadwilken  ```0.2.0``` supports shorthand usage like ```<Form.Input/>```. Errors will now  be correctly reflected on the labels automatically. Thanks for reporting this issue.
