### ISSUE TITLE
after submit, the input validation appear

### ISSUE THREAD

**Issue by white112** [zabute/formsy-semantic-ui-react#31]
I set the value of input as '' after submitted.
Input validation appears after submitted.

The desired result is to hide validation after submit.

![screenshot 2018-02-15 01 29 09](https://user-images.githubusercontent.com/22128210/36240323-a99260fa-11ef-11e8-912b-528d73cc5769.png)
![screenshot 2018-02-15 01 28 02](https://user-images.githubusercontent.com/22128210/36240324-a9caee66-11ef-11e8-9fee-0999c7d61ab8.png)

the desired result
![screenshot 2018-02-15 01 29 51](https://user-images.githubusercontent.com/22128210/36240341-c0ca97d8-11ef-11e8-8e60-84c08d186a4b.png)

**Comment by zabute** [comment]
Its becuase the inputs are ```dirty``` and need to be reset to their ``pristne`` state. See [here](https://github.com/formsy/formsy-react/blob/master/API.md#reset) and [here](https://github.com/formsy/formsy-react/blob/master/API.md#onSubmit)

**Comment by white112** [comment]
### formsy-semantic-ui-react doesn't support reset function.
I am only using ### formsy-semantic-ui-react

![screenshot 2018-02-16 13 27 37](https://user-images.githubusercontent.com/22128210/36317928-2d2889f2-131d-11e8-8a4a-caf2d05b66d1.png)

**Comment by zabute** [comment]
What do you get when you do this?
```js
handleSubmit(formData, resetForm) {
   resetForm()
}

**Comment by white112** [comment]
Right, It works.
Thanks @zabute
