### ISSUE TITLE
Support for React 16.x

### ISSUE THREAD

**Issue by dlaynes** [zabute/formsy-semantic-ui-react#32]
Hi. I am sorry if this is an inconvenient question, but I was wondering if there will be support for React 16 in the nearby future.
Thanks for creating this library.

**Comment by zabute** [comment]
It should work with React 16.

**Comment by dlaynes** [comment]
I'll try it with React 16 in a new project, however, I'm getting this warning, due to the library configuration.

npm WARN formsy-semantic-ui-react@0.3.2 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed.

**Comment by zabute** [comment]
I'll update that in the next release. You can ignore that warning for now

**Comment by zabute** [comment]
fixed in `0.3.3`
