### ISSUE TITLE
Would love to see this integrated with typescript

### ISSUE THREAD

**Issue by niteesh19** [zabute/formsy-semantic-ui-react#34]
I already love the way zabute/formsy provides a clean structure to SUR Forms.
But would be glad if someone adds support for `@types/formsy-semantic-ui-react` for the apps build in ts.

**Comment by felixmosh** [comment]
I've added re-export of the original semantic-ui type, https://github.com/zabute/formsy-semantic-ui-react/commit/f557fae13dccb0077ede331c0bccb93861503884

**Comment by felixmosh** [comment]
Full support was added in v2
