### ISSUE TITLE
Update peer dependencies

### ISSUE THREAD

**Issue by evangow** [zabute/formsy-semantic-ui-react#36]
2 quick things.

1) Is there any reason you can't update the peer dependencies for React to include 16? It looks like formsy uses 15 or 16.
https://github.com/formsy/formsy-react/blob/master/package.json

2) The link in the documentation that points to formsy-react is for the old repo. The new repo is at the link below
https://github.com/formsy/formsy-react/

**Comment by zabute** [comment]
fixed in `0.3.3`
