### ISSUE TITLE
Received `true` for a non-boolean attribute `inline`

### ISSUE THREAD

**Issue by Nosfistis** [zabute/formsy-semantic-ui-react#37]
Adding `inline` attribute to a `<Form.Input>` produces the following error:

> Warning: Received `true` for a non-boolean attribute `inline`.
> If you want to write it to the DOM, pass a string instead: inline="true" or inline={value.toString()}.

Adding `inline="true"` makes formsy complain about a non-boolean value given to a boolean prop.

This does not occur with normal semantic-ui `<Form>`.

**Comment by jwrubel** [comment]
I was able to work around this by wrapping the inputs in a `<Form.Group inline>`, and then wrapping each `<Input>` with `<Form.Field>`. Something like:

```
<Form>
  <Form.Group inline>
    <Form.Field>
      <Input/>
    </Form.Field>
    <Form.Field>
      <Input/>
    </Form.Field>
  </Form.Group>
</Form>
```

**Comment by zabute** [comment]
Fixed in 0.3.5

**Comment by willsmanley** [comment]
I received this issue again and I am > 0.3.5...

`
<Grid middle aligned center>
                        <Grid.Column>
                            <div className="ui large form">
                                <Segment stacked>
                                    <div className="field">
                                        <Input onChange={(e)=>this.setState({[e.target.name]: e.target.value})} value={this.state.email} type="text" name="email" placeholder="E-mail address" icon='user' iconPosition='left'/>
                                    </div>
                                    <div className="field">
                                        <Input icon='lock' iconPosition='left' onChange={(e)=>this.setState({[e.target.name]: e.target.value})} value={this.state.password} type="password" name="password" placeholder="Password"/>
                                    </div>
                                    <button className="ui fluid large black submit button" disabled={!(this.state.email && this.state.password && this.state.password.length > 6 && emailRegex({exact: true}).test(this.state.email))} onClick={() => this.submitForm()}>Login</button>
                                    <br/>
                                    <NavLink className="Forgot-Password" to='/forgot-password'>Forgot password?</NavLink>
                                </Segment>
                            </div>

                            <Message>
                                Don't have an account?

                                {this.props.location === 'homepage' ?
                                    <NavLink to={history.location.pathname} onClick={()=>this.props.switch()}><span className="bold"> Sign Up</span></NavLink>
                                    : <NavLink to="/register"> Sign Up</NavLink>
                                }

                            </Message>
                        </Grid.Column>
                    </Grid>
`

**Comment by willsmanley** [comment]
I have switched back to using the normal version of semantic except on Modals where I find it very useful. Problems like this make it much easier to just stick with <div className="ui xxx">
