### ISSUE TITLE
Error: Form Input requires a name property when used

### ISSUE THREAD

**Issue by Warhead007** [zabute/formsy-semantic-ui-react#38]
I cannot use Form from formsy-semantic-ui-react. And they show this error to me.
![image](https://user-images.githubusercontent.com/19686618/39011956-2c88d1a4-443d-11e8-8cea-fe3f67fe7798.png)
This is my index.js

`import` React from `'react';`
`import` ReactDOM from `'react-dom';`
`import` {BrowserRouter as Router , Route} from `'react-router-dom'`
`import` PlaceForm from `'./containers/AddPlace';`
`import` Home from './containers/Home'
`import` `'semantic-ui-css/semantic.min.css';`

`ReactDOM.render(`
`<Router>`
    `<div>`
        `<Route` path="/" exact component={Home} />
        `<Route` path="/addplace" component={PlaceForm} />
    `</div>`
`</Router>`
    `,` ``document.getElementById('root'));`

**Comment by zabute** [comment]
Looks like there is a missing `name` prop on one of your inputs. Try to find it. If there isn't one, let me have a look at the contents of PlaceForm so I can find the problem.

**Comment by Warhead007** [comment]
Wow. I set input name is `inputname` haha. Thx a lot.
