### ISSUE TITLE
How to use mask input with formsy?

### ISSUE THREAD

**Issue by Warhead007** [zabute/formsy-semantic-ui-react#41]
Hello. I would to use formsy with telephone number pattern (EX. 012-345-6789 or 012-345-678) and time  pattern (EX 17:00). Have some guide for this? 
PS.I love you work so much.

**Comment by dopeboy** [comment]
Check out the `matchRegexp` option [here](https://github.com/christianalfoni/formsy-react/blob/master/API.md#validators).

**Comment by felixmosh** [comment]
@Warhead007 after 2 years, I've added a new option (which is not published yet) `inputAs`.
This new option actually allows you to provide any input which works under the same "contract".
https://codesandbox.io/s/infallible-water-h9pwi?file=/src/App.js
