### ISSUE TITLE
Warning: Failed prop type: The prop `options` is marked as required in `FormSelect`, but its value is `undefined`.

### ISSUE THREAD

**Issue by inergy** [zabute/formsy-semantic-ui-react#50]
I made a quick CodeSandbox example which reproduces the error:

[![Edit Formsy Semantic UI - Form.Select options issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xv5mk55pno)

**Comment by mlund01** [comment]
Also ran into this same issue. Here are the first few lines of the console warning,
```
    index.js:2178 Warning: Failed prop type: The prop `options` is marked as required in `FormSelect`, but its value is `undefined`.
    in FormSelect (created by FormsyDropdown)
    in FormsyDropdown (created by Formsy(FormsyDropdown))
    in Formsy(FormsyDropdown)
    in Unknown
    ...
```

In this case I am not directly using the `Select` component, but `Form.Select`, and the `options` prop is definitely set, like the example above

**Comment by xavierartot** [comment]
You have to check if your array exist, don't forget the lifecycle:

```    const options = collections && collections.map(c => ({ key: c.id, text: c.name, value: c.name }))
```

and in the return(...) I'm testing again
```          { options &&
            <Form.Select
              control={Select}
              options={options}
            />
          }
```

**Comment by aminal** [comment]
The problem is that the `options` prop was never making it down to the SUIR `FormSelect`. PR https://github.com/zabute/formsy-semantic-ui-react/pull/52 resolves the issue by correctly passing the `dropdownProps`.
