### ISSUE TITLE
Cannot create TextArea without label with required

### ISSUE THREAD

**Issue by nelsyeung** [zabute/formsy-semantic-ui-react#53]
Using `TextArea` without `label` still creates a label.

The following code will create a red * even though no label is set:
```jsx
<TextArea required name='textarea' />
```
Using `Input` on the other hand won't have this problem:
```jsx
<Input required name='input' />
```
I'm expecting no label when it is not set like the `Input` component.

**Comment by zabute** [comment]
Use `passRequiredToField={false}`. See #18
