### ISSUE TITLE
semantic-ui-react's Popup is not working inside Formsy Form.

### ISSUE THREAD

**Issue by mallikarjunece** [zabute/formsy-semantic-ui-react#55]
Hi,

I am using `semantic ui react` Popup inside `formsy-semantic-ui-react` Form, which is not working.

Kindly let me know how to use Popup inside formsy-semantic-ui-react Form.

Thanks,
Mallikarjuna.

**Comment by felixmosh** [comment]
Do you have any reproduction example?
