### ISSUE TITLE
A way to reuse Form.Input as FormField and has an inline label

### ISSUE THREAD

**Issue by felixmosh** [zabute/formsy-semantic-ui-react#58]
Hi,
First of all, thank you for this great lib!

I'm looking for a way to render [labeled-input](https://react.semantic-ui.com/elements/input/#variations-right-labeled-basic) with the form field label, 
[The final result should look like that](https://codesandbox.io/s/v85vlqpk9y)

I know that I can re-implement your input functionality, but I don't think that this is a good practice.

I've tried to use `inputAs` with custom component, but looks like there are 2 issue:
1. prop-types are strict to SUIR Input
2. There is no form field label because of [this check](https://github.com/zabute/formsy-semantic-ui-react/blob/b97337732fe97c9aca9da5c6cbe96d1fc407fd3f/src/FormsyInput.js#L124)

[working example](https://github.com/zabute/formsy-semantic-ui-react/blob/b97337732fe97c9aca9da5c6cbe96d1fc407fd3f/src/FormsyInput.js#L124)

How do u suggest to fix this?

I've 2 suggested solution: 

1. 
- change `inputAs` prop type validation
- remove the [check](https://github.com/zabute/formsy-semantic-ui-react/blob/b97337732fe97c9aca9da5c6cbe96d1fc407fd3f/src/FormsyInput.js#L124) for `shortHandMode` (why it is there anyway?)
- add support for `inputAs` to accept react element (optional but will improve alot the usage of the component)

This will allow me to pass custom input to the `inputAs` prop like [here](https://github.com/zabute/formsy-semantic-ui-react/blob/b97337732fe97c9aca9da5c6cbe96d1fc407fd3f/src/FormsyInput.js#L124)

2. 
- change `inputAs` prop type validation
- be a ware of the implementation details and add `label` element to the custom input

```javascript
const LabeledInput = props => (
  <>
    <label>{props.label}</label>
    <Input
      {...props}
      label={{ basic: true, content: 'kg' }}
      labelPosition="right"
      placeholder="Enter weight..."
    />
  </>
);
```
Personally I don't like option # 2.

WDYT?

**Comment by felixmosh** [comment]
Add support for `inputAs` to be element solves the entire issue.
Check this https://gist.github.com/felixmosh/9ea975b4d020365bb1229748ef191450/revisions
Should I PR?

**Comment by zabute** [comment]
> remove the check for shortHandMode (why it is there anyway?)

Your'e right. It shouldn't be there. It appears I wrongly assumed only `Form.Input` and `Form.Textarea` could have labels.

> add support for inputAs to accept react element (optional but will improve alot the usage of the component)

`FormsyInput` was designed (at least at first) to work specifically with input components. It will probably break if someone passes in a non-input component.

SUIR 's `Form.Field` also has a `control` prop which we can use to render basically anything. I had been contemplating a rewrite of this lib based on solely utilizing that prop. I think that would enable what you want to achieve with allowing `inputAs` to accept a element or node.  Until then, removing the shortHand check would solve your immediate problem - it is also a bug.

**Comment by felixmosh** [comment]
Did you saw my inputAs implementation? It is basically 3 lines of code, and I agree with you that if there is a more generic approach to this problem We need to implement it, but as well, I think that for a short term solution exposing input as to get ReactElement (Sui Inputs with specific config) would be awesome.

In fact I’ve patched the lib, and my solution works great. I can make a PR with it.

**Comment by zabute** [comment]
> I can make a PR with it.

Yeah sure go ahead.

**Comment by felixmosh** [comment]
I've updated this implementation to formsy-react v2
