### ISSUE TITLE
Preparation to formsy-react v.2

### ISSUE THREAD

**Issue by felixmosh** [zabute/formsy-semantic-ui-react#65]
Hi,

formsy-react gonna release a major version 2, is should solve many bugs in v1.
Let's open to discussion of how would we want this lib to adjust to v2 at this thread.

I want to contribute :]

**Comment by rkuykendall** [comment]
I'm also open to contributing.

BTW The release can happen as soon as I can get it running successfully on my own work codebase (ts type conflicts right now), or some people with better codebases confirm it's working. So could be very soon.

**Comment by felixmosh** [comment]
@zabute you wanted to refactor the lib, what did you want to change?

**Comment by evangow** [comment]
Is this still happening? I don't even need a full re-write. I just would love to get rid of some of the warning in my console about deprecated react methods (i.e. componentWillMount, componentWillReceiveProps, and componentWillUpdate)

**Comment by rkuykendall** [comment]
BTW update to formsy release: Should be happening this week. We have 1 final types PR that has already undergone a round of review. It should be mergeable tomorrow, then a final beta release, and probably a 2.x on Saturday morning so I can spend the weekend watching for reports?

**Comment by rkuykendall** [comment]
Formsy 2.0.0 is now released. The upgrade should be pretty painless. The small code changes are documented in the readme. I'm also happy to help.
