### ISSUE TITLE
Select component stateless

### ISSUE THREAD

**Issue by zhenyanghua** [zabute/formsy-semantic-ui-react#9]
Is there a proper way to retrieve selected value from the Select component? This is a stateless component, when using `refs` to get the value from it, react warning will show up saying calling `refs` on a stateless component might fail.

**Comment by zabute** [comment]
Sorry for the late reply, @zhenyanghua . 

The form keeps an array of refs to the inputs. You can set a ref on it and then retrieve the values:
```jsx
<Form ref={ref => this.form =ref}>
  <Select .../>
</Form>

this.form.formsyForm.inputs[0].getValue(); 
```
If You are not using the unified ```<Form/>``` api from this library, you can find the refs in ```this.form.inputs```. 

However, I dont think having only some of the components be stateless is a good idea. The proxy components (all of which are stateless) will have to be converted to regular components. I will  work on this as soon as I can.
